path:
  ckpt_path: "/project/AI-team/exp/chungtran/tts/fastspeech2/Adaptation_Multilingual/Adaptation_Multilingual_Hifigan_L1"
  log_path: "/project/AI-team/exp/chungtran/tts/fastspeech2/Adaptation_Multilingual/Adaptation_Multilingual_Hifigan_L1"
  result_path: "/project/AI-team/exp/chungtran/tts/fastspeech2/Adaptation_Multilingual/Adaptation_Multilingual_Hifigan_L1"
optimizer:
  batch_size: 8
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 10  #100
  synth_step: 20 #1000
  val_step: 20 #1000
  save_step: 100 #100000
